name: MoonGPS
version: '${project.version}'
main: org.ney.moongps.MoonGPS
api-version: '1.20'
author: Ney
description: Navigator to the marks of your server
website: https://t.me/NeyOff

commands:
  gps:
    description: Navigator to the server marks
    usage: /gps <mark>
    aliases: [navigator, moongps]

permissions:
  moongps.use:
    description: Access to the navigator
    default: true
  moongps.list:
    description: Viewing the list of marks
    default: true
  moongps.set:
    description: Creating marks from the game
    default: op
  moongps.delete:
    description: Deleting marks from the game
    default: op
  moongps.reload:
    description: Reloading the plugin configuration
    default: op
